AvtoInfo/AvtoInfo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("cars.urls")),
    path("user/", include("users.urls")),
    path("admin/", admin.site.urls),
]

AvtoInfo/cars/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from cars import views
from cars import views_api


app_name = "cars"

router = DefaultRouter()
router.register(r"cars", views_api.CarViewSet)

urlpatterns = [
    path("", views.get_cars, name="home"),
    path("add/", views.add_car, name="add_car"),
    path("<int:car_id>/", views.car_detail, name="car_detail"),
    path("<int:car_id>/edit/", views.edit_car, name="edit_car"),
    path("<int:car_id>/delete/", views.delete_car, name="delete_car"),
    path("api/", include(router.urls)),
]

AvtoInfo/users/urls.py
from django.urls import path

from users import views

app_name = "users"


urlpatterns = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name="registration"),
    path("profile/", views.profile, name="profile"),
    path("logout/", views.logout, name="logout"),
]

AvtoInfo/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):

    class Meta:
        db_table: str = "Users"
        verbose_name: str = "User"
        verbose_name_plural: str = "Users"

    def __str__(self) -> str:
        return self.username

AvtoInfo/users/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm,
    UserChangeForm,
)

from users.models import User


class UserLoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = [
            "username",
            "password",
        ]


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "password1",
            "password2",
        ]

    email = forms.CharField()


class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = [
            "username",
            "email",
        ]

    email = forms.CharField()

AvtoInfo/users/views.py
from typing import TYPE_CHECKING

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import auth

from users.forms import (
    UserLoginForm,
    UserRegistrationForm,
    UserProfileForm,
)
from cars.models import Car

if TYPE_CHECKING:
    from django.http import HttpResponse, HttpRequest


def login(request: "HttpRequest") -> "HttpResponse":

    if request.method == "POST":
        form = UserLoginForm(data=request.POST)

        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(username=username, password=password)

            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse("cars:home"))
            else:
                form.add_error(None, "Неверный логин или пароль")
    else:
        form = UserLoginForm()

    context = {
        "title": "AvtoInfo - Authentication",
        "form": form,
    }

    return render(request, "users/login.html", context)


def registration(request: "HttpRequest") -> "HttpResponse":

    if request.method == "POST":
        form = UserRegistrationForm(data=request.POST)

        if form.is_valid():
            form.save()

            user = form.instance
            auth.login(request, user)

            return HttpResponseRedirect(reverse("users:profile"))
    else:
        form = UserRegistrationForm()

    context = {
        "title": "AvtoInfo - Registration",
        "form": form,
    }

    return render(request, "users/registration.html", context)


@login_required
def profile(request: "HttpRequest") -> "HttpResponse":

    user_cars = Car.objects.filter(owner=request.user)
    if request.method == "POST":
        form = UserProfileForm(
            data=request.POST,
            instance=request.user,
        )

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse("users:profile"))

    else:
        form = UserProfileForm(instance=request.user)

    context = {
        "title": "AvtoInfo - Profile",
        "user_cars": user_cars,
        "form": form,
    }

    return render(request, "users/profile.html", context)


@login_required
def logout(request: "HttpRequest") -> "HttpResponse":
    auth.logout(request)
    return redirect(reverse("users:login"))

AvtoInfo/templates/users/login.html
{% extends "cars/base.html" %}
{% load static %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                <h2 class="text-center mb-4">Аутентификация</h2>

                {% if form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for error in form.non_field_errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}

                <form action="{% url "users:login" %}" method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_username" class="form-label">Логин</label>
                        <input type="text" class="form-control" name="username" id="id_username"
                        value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                        placeholder="Введите ваш логин" required>
                    </div>
                    <div class="mb-3">
                        <label for="id_password" class="form-label">Пароль</label>
                        <input type="password" class="form-control" name="password" id="id_password" placeholder="Введите ваш пароль" required>
                    </div>
                    <button type="submit" class="btn btn-dark btn-block">Войти</button>
                </form>
                <div class="mt-3">
                    <a href="{% url "users:registration" %}">Регистрация</a>
                </div>
                <hr>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

AvtoInfo/templates/users/profile.html
{% extends "cars/base.html" %}
{% load static %}


{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-5">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Изменить данные</h3>
                    <form action="{% url "users:profile" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Логин*</label>
                                <input type="text" class="form-control" id="id_username"
                                    name="username"
                                    placeholder="Введите ваш логин"
                                    value="{{ form.username.value }}" required>
                                    {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Электронный адрес*</label>
                                <input type="email" class="form-control" id="id_email"
                                    name="email"
                                    placeholder="Введите вашу почту *youremail@example.com"
                                    value="{{ form.email.value }}" required>
                                    {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
            <div class="container mt-5">
                <h3 class="text-center mb-4">Ваши машины</h3>
                <div>
                    {% for car in user_cars %}
                    <div>
                        <h2 id="heading{{ car.id }}">
                            <div class="d-flex justify-content-between align-items-center">
                                <span>{{ car.make }} {{ car.model }} ({{ car.year }})</span>
                                <div>
                                    <a href="{% url 'cars:edit_car' car.id %}" class="btn btn-warning">Редактировать</a>
                                    <a href="{% url 'cars:delete_car' car.id %}" class="btn btn-danger" onclick="return confirm('Вы уверены, что хотите удалить машину?')">Удалить</a>
                                </div>
                            </div>
                        </h2>
                    </div>
                    {% empty %}
                    <h4 class="text-center mb-2">Машин пока нет.</h4>
                    {% endfor %}
                </div>
            </div>
    </div>
</div>
{% endblock content %}

AvtoInfo/templates/users/registration.html
{% extends "cars/base.html" %}
{% load static %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Регистрация</h2>
                <form action="{% url "users:registration" %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label">Логин*</label>
                            <input type="text" class="form-control" id="id_username"
                                value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                name="username"
                                placeholder="Введите желаемый логин" required>
                                {% if form.username.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Почта*</label>
                            <input type="email" class="form-control" id="id_email"
                                value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                name="email"
                                placeholder="Введите желаемую почту" required>
                                {% if form.email.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label">Пароль*</label>
                            <input type="password" class="form-control" id="id_password1"
                                value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                name="password1"
                                placeholder="Введите желаемый пароль" required>
                                {% if form.password1.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                            <input type="password" class="form-control" id="id_password2"
                                value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                name="password2"    
                                placeholder="Подтвердите пароль" required>
                                {% if form.password2.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                                {% endif %}
                        </div>
                    </div>
                    <button type="submit"
                        class="btn btn-dark btn-block">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}